### ISSUE TITLE
Authorization Violation

### ISSUE THREAD

**Issue by timkofu** [alpacahq/example-hft#3]
Hi,

I keep getting this error when I run it:

> Traceback (most recent call last):
  File "/home/alpaca/.alpaca/lib/python3.7/site-packages/nats/aio/client.py", line 244, in connect
    yield from self._process_connect_init()
  File "/home/alpaca/.alpaca/lib/python3.7/site-packages/nats/aio/client.py", line 1325, in _process_connect_init
    raise NatsError("nats: " + err_msg.rstrip('\r\n'))
nats.aio.errors.NatsError: nats: 'Authorization Violation'

This happens even after generating fresh credentials.

**Comment by ttt733** [comment]
Hello Tim, do you have an Alpaca brokerage account, or are you only authorized for paper trading? Your brokerage account needs to be approved for you to have access to the Polygon streaming data.

**Comment by timkofu** [comment]
Hi. Ah, that's the issue then; I have a paper-trading account.

**Comment by vit-h-zz** [comment]
how to write a robot without access to quotes?
I just signup for paper trading.

**Comment by timkofu** [comment]
Alphavantage have an API with a reasonable free tier.

**Comment by anggarizkia** [comment]
> Hai,
> 
> Saya terus mendapatkan kesalahan ini ketika saya menjalankannya:
> 
> > Traceback (panggilan terakhir terakhir): 
> > File "/home/alpaca/.alpaca/lib/python3.7/site-packages/nats/aio/client.py", baris 244, dalam 
> > hasil koneksi dari self._process_connect_init() 
> > File "/home/alpaca/.alpaca/lib/python3.7/site-packages/nats/aio/client.py", baris 1325, di _process_connect_init 
> > naikkan NatsError("nats: " + err_msg.rstrip('\r\n ')) 
> > nats.aio.errors.NatsError: nats: 'Pelanggaran Otorisasi'
> 
> Hal ini terjadi bahkan setelah membuat kredensial baru.

The error message you receive, "Authorization Violation," indicates that there was a problem with authorization when trying to connect to the NATS server.  This can be caused by several reasons:

 1. **Invalid Credentials**: Make sure that the credentials (such as API key and secret) you use are correct.  Make sure there are no errors in copying or saving these credentials.

 2. **Insufficient Permissions**: Make sure that the credentials you use have sufficient permissions to access the NATS server.  Some NATS servers may require special permissions to access some subjects or topics.

 3. **Incorrect Server URL**: Make sure that you are using the correct NATS server URL.  This is the NATS server address that your client must contact.  Make sure there are no errors in the URL you use.

 4. **Firewall or Network Restrictions**: Ensure that there are no firewalls or network restrictions blocking connections to the NATS server.  Try checking if there are any firewall rules affecting your connection.

 5. **Check Server Logs**: If you have access to the NATS server logs, check the logs to see if there is more information about the reason "
